name: Golang CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2 

      - name: Go Format
        run: go fmt ./...
      
      - name: Go Fix
        run: go fix ./...

      - name: Go Build
        run: go build -v ./...
